### ISSUE TITLE
Integrate renderer directly in MPS

### ISSUE THREAD

**Issue by eugenschindler** [DSLFoundry/mps-langvis#3]
It would be much better to see the visualization directly in MPS instead of having to call PlantUML as a separate tool.

**Comment by RemiBosman** [comment]
Implemented in PumlPanel branch

**Comment by diederikd** [comment]
Guess this is done.

**Comment by eugenschindler** [comment]
Yes, thanks to @diederikd we are quite far again. But not all functionality from the PumlPanel branch has yet been remade. We are missing buttons.

**Comment by eugenschindler** [comment]
I will move this to another issue
