### ISSUE TITLE
Add packages to the visualization

### ISSUE THREAD

**Issue by klemensschindler** [DSLFoundry/mps-langvis#6]
Map MPS virtual packages to PlantUML packages.

**Comment by RemiBosman** [comment]
Implemented in PumlPanel branch

**Comment by JoostvanPinxten** [comment]
I orignally posted my issue to: https://github.com/JetBrains/MPS-extensions/issues/260

I see that Remi has done some work on this quite some time ago, but that this branch hasn't been merged.

**Comment by klemensschindler** [comment]
The issue has been addressed in 353c6eeda50245946cb8b0981b945deef0decd16. This is already merged into the master branch.
